# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: "." # ${{ github.workspace }} # location for the settings.xml file
    - id: install-gpg-key
      name: Install gpg key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG
    - id: add-publish-key
      name: Add publish key
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.GPG_PASS_PHRASE }} \
            clean deploy
    
